### ISSUE TITLE
Cannot mock sibling calls or view calling arguments

### ISSUE THREAD

**Issue by kevupton** [defi-wonderland/smock#109]
**Describe the bug**
Unable to test methods on the same contract

**Reproduction steps**

```typescript

    it('should call a method on the same contract and test it', async () => {

      someContract.check.returns(false);

      const result = await someContract.doCheck(arg1, arg2, arg3);

      expect(result).to.be.false;
      expect(someContract.check).to.have.been.calledWith(arg1, arg2, arg3);
    });
```

**Expected behavior**

It should have a function call on `check` method, with those arguments supplied.

**Comment by wei3erHase** [comment]
hi @kevupton, as i'd like to see a way of testing internal function calls, so far is not supported and this is the expected behaviour
