### ISSUE TITLE
feat request: return hardhat errors on failed factories

### ISSUE THREAD

**Issue by JChiaramonte7** [defi-wonderland/smock#110]
**Is your feature request related to a problem? Please describe.**
We were getting an `unable to generate smock spec from string` error when trying to construct a fake from an interface contract. It wasn't directly clear from smock what the issue was. In our case, we found the root cause to be that there were two different IERC20 artifacts in the repo -- which breaks `getContractFactory`. See hardhat error: [multiple artifacts for a contract issue ](https://hardhat.org/errors/#HH701)

**Describe the solution you'd like**
We should probably surface errors when parsing the `spec` string
- Solution A: Log out caught errors (probably not ideal because we rely [optional catch binding](https://2ality.com/2017/08/optional-catch-binding.html) to parse `spec`)
- Solution B: Store caught errors and log them if all tries fail

**Additional context**
https://github.com/defi-wonderland/smock/blob/d6397b7ed3b414395f43a97f697ef22fb46054a2/src/factories/ethers-interface.ts#L6-L19

**Comment by wei3erHase** [comment]
hi @JChiaramonte7,
thanks for pointing this out, we've created a task to the roadmap to address this issue,
hope this is fixed soon :)

**Comment by wei3erHase** [comment]
closed with #127
