### ISSUE TITLE
feat request: edit multiple variables at once

### ISSUE THREAD

**Issue by tonykogias** [defi-wonderland/smock#111]
**Is your feature request related to a problem? Please describe.**
If someone wants to edit more than one variable using a mock contract, the user would have to repeat using the `setVariable` function. I believe it would help if there was a function that would edit multiple variables at once (like smock's v1 `smodify.put`)

**Comment by wei3erHase** [comment]
hi @tonykogias, thanks for the issue AND the PR #112 , i've made some comments on it, and we're actually establishing a bounty for it so keep tuned
i'm leaving this issue open until there's a closure with the task,
bests!

**Comment by wei3erHase** [comment]
[👀👀👀](https://app.dework.xyz/smock/main-project-3127?taskId=ee64cd9f-e82e-4b1a-af4b-176c04ec43c3)

**Comment by tonykogias** [comment]
Hey @wei3erHase! Thanks for the comments I will look into it later today and make the changes. I really appreciate the bounty that was added as well! Cheers :)

**Comment by 0xGorilla** [comment]
In order to complete the task:
* The method should be strongly typed
* Multiple tests need to be added
* Check different combination of variables with different types
* Set all variables of a contract at the same time using the new method
* Any other test you consider necessary

**Comment by 0xGorilla** [comment]
@tonykogias please add your address to the issue in dework so we can send you the bounty 🥳

**Comment by tonykogias** [comment]
> @tonykogias please add your address to the issue in dework so we can send you the bounty 🥳

I have linked my metamask account to my profile, is there something else I have to do? Should I send you my address here? I am not that used to dework.

**Comment by 0xGorilla** [comment]
Sent the 200 USDC your way! There are lots of other issues if you want to continue contributing ❤️

**Comment by tonykogias** [comment]
Thanks! I appreciate it I will definitely have a look at those issues.
