### ISSUE TITLE
feat request: add reading calls msg data and value

### ISSUE THREAD

**Issue by hickscorp** [defi-wonderland/smock#114]
It'd be great to know when a mock is called, what was the raw shape of the `msg` structure.
In our case, we need to check that a `payable` function was called with the correct amount of funds.

**Comment by sraver** [comment]
Same here, I'm trying to test a contract that sends assets to another, and depending if the token is ERC20 or native coin I need to check the `value` to see if it's correct. I didn't find a way to do it :/

**Comment by 0xGorilla** [comment]
Could you guys read the PR I just linked and tell me what you think? Does that solve the issue?

**Comment by sraver** [comment]
@0xGorilla that looks indeed amazing! 

Thanks for solving this :pray:
