### ISSUE TITLE
BUG Functions that returns an array, always returns unexpected amount of data

### ISSUE THREAD

**Issue by stefanandy** [defi-wonderland/smock#121]
**Describe the bug**
When trying to mock the return of an functions that returns and array of addresses, no matter what output you give in the returns function, you will always get the error, "Error: Transaction reverted: function returned an unexpected amount of data"

**Reproduction steps**
1. Create a sc that have a function that will return an array of addresses.
2. Create a fake for the sc.
3. Mock the function output.
4. Call the function from a sc that is calling the fake.
5. Get the error

**Expected behavior**
Returned the mocked values

**Screenshots**
<img width="817" alt="image" src="https://user-images.githubusercontent.com/31569796/174504950-bdef098b-d892-43af-9112-e7c7c2c1d43b.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/31569796/174504965-41aac381-252d-4f0c-9648-66d3dea4d558.png">

**System Specs:**

- OS: macOS 12.4
- solidity: 0.6.12
- smock: 2.0.7
- hardhat: 2.0.8

**Comment by wei3erHase** [comment]
arrays are currently not supported, this is related to #31 
closing this issue so that we have only 1 task for this,
thanks for the time taken describing the bug :)
