### ISSUE TITLE
Add a way to view internal variables value

### ISSUE THREAD

**Issue by 0xGorilla** [defi-wonderland/smock#14]
Just as `await mock.setVariable('_myVar', 123);`
I believe we should have: `await mock.getVariable('_myVar');` that returns the current value of the variable

**Comment by smartcontracts** [comment]
Hmmm interesting. We would essentially have to work backwards from the storage slot => variable value, which requires some non-trivial parsing. Need to think about this a little more, could get quite complex.

**Comment by superical** [comment]
+1 to this feature. 
I was wondering if I could do this and I'm glad that I'm not the only one thinking this might be useful.

**Comment by ashhanai** [comment]
Any progress here? I would love to start using `getVariable` functionality.
