### ISSUE TITLE
Deploy in mocks doesn't have typings

### ISSUE THREAD

**Issue by 0xGorilla** [defi-wonderland/smock#16]
When doing:
```
counterFactory = await lopt.mock<Counter>('Counter');
await counterFactory.deploy(...);
```

The deploy does not have the types inherited. I suppose we should use the CounterFactory from typechain

**Comment by smartcontracts** [comment]
I guess if you want the types you probably need to update `mock` to take the `ContractFactory` as a second type parameter.

**Comment by 0xGorilla** [comment]
It is pretty complicated but we can manage to do it without 😄
