### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'events')

### ISSUE THREAD

**Issue by carlomigueldy** [defi-wonderland/smock#163]
**Describe the bug**

After mock contract deployment, it just throws the exception.

**Reproduction steps**

1. Create a very basic contract
2. Initialize a simple test suite and use @defi-wonderland/smock later version with Hardhat latest version
3. Deploy the mock contracts on the test suite
4. Run the unit test and observe it failing throwing the exception `Cannot read properties of undefined (reading 'events')`

**Expected behavior**

It should throw exception after mock contract deployment in `before` or `beforeEach` hooks
The exception to throw: `Cannot read properties of undefined (reading 'events')`

**Screenshots**

![Screenshot from 2022-10-06 11-40-50](https://user-images.githubusercontent.com/45052332/194209069-6c23fd2f-a5ad-4d79-9546-94bb2543e091.png)

![Screenshot from 2022-10-06 11-40-17](https://user-images.githubusercontent.com/45052332/194208985-243e2d45-66de-4d86-8a14-bd20d627db8a.png)

**System Specs:**

- OS: Pop_OS
- Package Version (or commit hash): ^2.3.0

**Additional context**

**Comment by wei3erHase** [comment]
yoo @carlomigueldy, code looks solid to me, have u tried a `beforeAll` instead of `before`?
blz submit full `SavePakistanSmock.ts` to give a proper-er advice

**Comment by carlomigueldy** [comment]
> yoo @carlomigueldy, code looks solid to me, have u tried a `beforeAll` instead of `before`? blz submit full `SavePakistanSmock.ts` to give a proper-er advice

gm bro, unfortunately there is not `beforeAll` available only `before` and `beforeEach` and so I tried `beforeEach` and still throwing the same exception

Here be the entire test suite as you ask:
```ts
import { MockContract, MockContractFactory, smock } from "@defi-wonderland/smock";
import { SavePakistan, SavePakistan__factory } from "../typechain-types";
import chai, { expect } from "chai";
import { TokenVariant } from "../utils";
import { BigNumber } from "ethers";

chai.should();
chai.use(smock.matchers);

describe("Smock: SavePakistan", () => {
  let savePakistanFactory: MockContractFactory<SavePakistan__factory>;
  let savePakistan: MockContract<SavePakistan>;

  before(async () => {
    savePakistanFactory = await smock.mock<SavePakistan__factory>("SavePakistan");

    savePakistan = await savePakistanFactory.deploy();
    console.log("savePakistanMock.address", savePakistan.address, "...");
  });

  it("should be cool", async () => {
    console.log("COOL");
  });

  // it("should make it", async () => {
  //   console.log("savePakistanMock.address", savePakistan.address, "...");
  //   savePakistan.mintByPayingEth
  //     .whenCalledWith(TokenVariant.HygieneKit, BigNumber.from("1"))
  //     .returns(undefined);
  // });

  // it("should mock the shit out of it", async () => {
  //   savePakistanMock.USDC_ADDR.returns("carlo");

  //   const usdcAddr = await savePakistanMock.USDC_ADDR();
  //   console.log("usdcAddr", usdcAddr);
  // });

  // it("should call getters", async () => {
  //   expect(await mock.count()).to.equal(1);
  // });

  // it("should call methods", async () => {
  //   await mock.add(10);
  //   expect(await mock.count()).to.equal(11);
  // });

  // it("should be able to override returns", async () => {
  //   mock.count.returns(123);
  //   expect(await mock.count()).to.equal(123);
  // });

  // it("should be able to override a function that reverts", async () => {
  //   mock.doRevert.returns(true);
  //   expect(await mock.doRevert()).to.equal(true);
  // });

  // it("should be able to check function calls", async () => {
  //   await mock.add(10);
  //   expect(mock.add).to.be.calledOnceWith(10);
  // });
});
```

**Comment by carlomigueldy** [comment]
> Copied and run, it works cool. <img alt="image" width="516" src="https://user-images.githubusercontent.com/84595958/194327464-f7e552eb-c30b-48c7-90c1-69996883af25.png">
> 
> Because of our repo structure, I had to change the import to:
> 
> ```ts
> import { SavePakistan, SavePakistan__factory } from "../../typechained";
> ```
> 
> Idk if it had something to do...

damn, can you share me your repo + dependencies? lol

**Comment by wei3erHase** [comment]
Sure fren, i'd recommend it to bootstrap and boost-up any project:
https://github.com/defi-wonderland/solidity-hardhat-boilerplate

**Comment by carlomigueldy** [comment]
> Sure fren, i'd recommend it to bootstrap and boost-up any project: https://github.com/defi-wonderland/solidity-hardhat-boilerplate

The suggested template/boilerplate for Hardhat works very well! 

So I feel safe to close this issue as this template works the best :+1:

**Comment by yehted** [comment]
I'm having this issue as well - @carlomigueldy did you ever figure out why the repo structure caused this error?
