### ISSUE TITLE
Deploy a Fake/Mock contract on a specific address

### ISSUE THREAD

**Issue by wei3erHase** [defi-wonderland/smock#47]
There are sometimes addresses that can be hardcoded on a contract, and in unit testing those addresses are empty.

Ex.:
```js
address public constant override WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
```

`Error: Transaction reverted: function call to a non-contract account`

It'd be nice to be able to deploy a contract on a specific address, instead of having to pass that address through a constructor, and having to modify the contract just for the testing.

Ex.:
```js
const wethFactory = smock.mock<ERC20__factory>('ERC20');
weth = await wethFactory.deploy({address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'});
```

{\\__/}
( • . •)
/ > 💾

**Comment by smartcontracts** [comment]
Should be pretty easy. I'll handle it.

**Comment by smartcontracts** [comment]
Oh wait, isn't this already supported for Fakes? https://github.com/defi-wonderland/smock/blob/3651c26cba5e85892f052aaf877cf6959bd72d5b/src/sandbox.ts#L41

**Comment by smartcontracts** [comment]
I would try `const fake = smock.fake(spec, { address: '...' })` and see if it works. If so, we should add this to the docs.

**Comment by 0xGorilla** [comment]
It is available for `fakes`, not for `mocks`.

I will try to make it work by using [hardhat_setCode](https://hardhat.org/hardhat-network/reference/#hardhat-setcode) functionality

**Comment by 0xGorilla** [comment]
Implementing this feature in `mocks` will be a bit tricky since we should use `hardhat_setCode` (available after hardhat 2.4.0) and then copy the storage as well.

@wei3erHase can you solve your issue with just a `fake`?

@smartcontracts I added some tests and docs for the initialization of `fakes` at a specific address: #48

**Comment by wei3erHase** [comment]
didn't know about this! i will certainly give it a try, many thanks both!

**Comment by superical** [comment]
@smartcontracts Ohh thanks! This could work too! Must I always deploy a fake with a contract? Or can a fake be just a standalone wallet at a specific address?

Right now, what I have just tried is I deployed a fake of `myOtherContract` as `myOtherContractFake` but I'm not really using the fake other than its wallet.

**Comment by smartcontracts** [comment]
I see. If you're just trying to call a contract from a specific address, I would use: https://hardhat.org/hardhat-network/reference/#hardhat-impersonateaccount

**Comment by superical** [comment]
Awesome! Thanks @smartcontracts!😊
