### ISSUE TITLE
Deploy mock with custom sender

### ISSUE THREAD

**Issue by 0xGorilla** [defi-wonderland/smock#63]
**Describe the bug**
Currently, it is not possible to deploy a mock with a custom sender since the connect returns the contract factory and not the MockFactory

**Reproduction steps**
Run `(await smock.mock('MyContract')).connect(someone).deploy(...)`

**Expected behavior**
The connect method should be overridden in order to return the mock factory when executed

**Comment by smartcontracts** [comment]
I'm a little confused by this. What's the desired behavior?

**Comment by 0xGorilla** [comment]
Right now you are not able to deploy a mock while also using the `connect` method, it would be great if it would work... Can you deal with this one?

**Comment by smartcontracts** [comment]
Ohhh I see the issue. Ok I can tackle this but will probably can't get to it until thursday.
