### ISSUE TITLE
Missing ehtereumjs-vm dependency

### ISSUE THREAD

**Issue by b0dhidharma** [defi-wonderland/smock#70]
**Describe the bug**
Direct installation of `smock` thats not work out of the box. When running my tests an error `Error: Cannot find module '@nomiclabs/ethereumjs-vm/dist/exceptions'` is thrown.
This is fixable by installing that dependency on the project, but its a pretty weird behaviour, honestly.

**Reproduction steps**

1. Start a project
2. Install smock
3. Try to use it (at least Im using `fake`)

**Expected behavior**
Work out of the box.

**Screenshots**
Can't show without doxing myself - approach via DM if necessary. 

**System Specs:**

- OS: Ubuntu
- Package Version (or commit hash): 2.0.3

**Additional context**
n/a

**Comment by smartcontracts** [comment]
Ah okay I see the problem. Will see if I can work out a quick fix.
