### ISSUE TITLE
Support for packed storage edition

### ISSUE THREAD

**Issue by 0xGorilla** [defi-wonderland/smock#8]
> Statically-sized variables (everything except mapping and dynamically-sized array types) are laid out contiguously in storage starting from position 0. Multiple items that need less than 32 bytes are packed into a single storage slot if possible

Add support for packed storage in lopt, both for variables and structs.

Tests representing this functionality can be found skipped at `editable-storage-logic.spec.ts`

**Comment by smartcontracts** [comment]
Closed by #23
