### ISSUE TITLE
Setting a FakeContract return value as a struct "Error: call revert exception"

### ISSUE THREAD

**Issue by richard-massless** [defi-wonderland/smock#94]
**Describe the bug**
When setting the return value of the function on a FakeContract the call is reverted.

**Reproduction steps**
```sol
    mapping(uint256 => SomeType) public typeMap

    struct SomeType {
        uint256 id;
        string name;
    }
```

```ts
  fakeContract.getType.returns({
    id: BigNumber.from(1),
    name: "Type1",
  });
```
Returns `Error: call revert exception`

**Expected behavior**
Setting the return value of `fakeContract.getType` to mirror the solidity struct will should be able to be set without causing a revert.

**Workaround**
Setting the returns value of  `fakeContract.typeMap` as an array will not cause the `Error: call revert exception`

```ts
  fakeContract.typeMap.returns([
   BigNumber.from(1),
    "Type1",
  ]);
```

**Workaround issue**
Let me know if this should  be a new ticket but it appears heavily related:
When testing a function on the real contract, which in turn calls `fakeContract.typeMap()` the response is: 
`Error: Transaction reverted: function returned an unexpected amount of data`

**Comment by 0xGorilla** [comment]
This is finally fixed! 🥳 

If you would like to try it out right now you could install the canary version: `0.0.0-294819d5`, if not, it will be released soon.
